/**
 * The Zine — "experimental Poetry", a web recreation of the zine I made for
 * my modern poetry class (the original PDF is linked at the top). Poems and
 * commentary are reproduced verbatim; the ASCII mascots come from 東方AA纏メ処
 * (modified for the zine — see Works Cited). The scanned Hagiwara Kyōjirō
 * poem from the print zine is cited rather than reproduced.
 */
import { Router } from '../router';
import { makeArticleLevel } from './article';
import zineUrl from '../assets/Zine.pdf';

// the zine's recurring mascot, waving the reader in (始まるよ！ = "here we go!")
const AA_HELLO = String.raw`      ＿＿＿
   ´>    ｀ヽ、
 _,.'-=[＞＜]=.,_
  ヽi <ﾚﾉλﾉ)ﾚ〉'
  ﾉﾚ§ﾟ ヮﾟﾉ iゝ        始まるよ！
  ｀k'_.〉｀=' !つ
    i_ﾉ'i!￣i!>、
   ~'i,ﾝ T,ﾝ"~`;

// tea time (ここすき！ = "love this part!")
const AA_TEA = String.raw`   ＜´  ＼
   /!＞＜!ヽ
   ' -―-  ヽ         ＿＿＿＿＿＿＿＿
 ＜ ノﾉ 从从 i） ＞   ／
   ﾉﾉ i ﾟ ヮﾟﾉ!!   ＜  ここすき！
   （つ旦 O         ＼＿＿＿＿＿＿＿＿
    と_＿)_)   旦~旦~旦~旦~ 旦~旦~旦~旦~`;

// goodbye (またね！ = "see you!")
const AA_BYE = String.raw`   ＜´  ＼        ☆
   /!＞＜!ヽ     ／
   ' -―-  ヽ
 ＜ ノﾉ 从从 i） ＞
   ﾉﾉ i ＾ヮﾟﾉ!!    ＜またね！
   < i つ且⊂
    く/_/__|〉
      し'ﾉ`;

// "Stars" — the space between the asterisks IS the poem
const STARS_BOX = String.raw`*    *    *    *    *    *    *    *    *    *    *    *    *
*                                                           *
*                                                           *
*                                                           *
*                                                           *
*    some space created for you to imagine the actual       *
*    distance                                               *
*                                                           *
*                                                           *
*                                                           *
*                                                           *
*                                                           *
*                                                           *
*    *    *    *    *    *    *    *    *    *    *    *    *`;

// "Behavior Tree in COVID Pandemic" — the tree, re-typeset for the web
const BEHAVIOR_TREE = String.raw`(?)
 ├─ (→) ─ Is sleepy? ────────► Go to bed.
 │
 ├─ (→) ─ Is hungry? ────────► (~?) ─┬─ Order delivery foods.
 │                                   ├─ Cook instant noodles.
 │                                   └─ Cook some real foods.
 │
 ├─ (→) ─ Has any assignment? ─► (~?) ─┬─ (→) ─┬─ Pick an assignment to finish.
 │                                     │       └─ Finish the picked assignment.
 │                                     └─ Play some games while being guilty
 │                                        of not doing the assignments.
 │
 └─ Philosophical meditation and chores.`;

export function makeZineLevel(router: Router) {
  return makeArticleLevel(router, 'zine', 'THE ZINE', (inner) => {
    inner.innerHTML = `
      <h1>experimental Poetry</h1>
      <p class="abstract">A zine for my modern poetry class — structural beauties, scientific diagrams,
        and ASCII arts. Recreated for the web; the print original is
        <a href="${zineUrl}" target="_blank" rel="noopener">here as a PDF</a>.</p>
      <div class="rule"></div>

      <div class="zine-paper">
        <div class="zine-cover-title">experimental<br>Poetry</div>
        <div class="zine-byline">by Yunhao Luo</div>
        <pre class="aa">${AA_HELLO}</pre>
        <div class="zine-credit">© 2026 Yunhao Luo · text &amp; layout licensed
          <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener">CC BY-NC-ND 4.0</a>.
          ASCII mascots adapted from 東方AA纏メ処 (see Works Cited).</div>
      </div>

      <div class="zine-paper">
        <h2>Intro</h2>
        <p>Welcome to my world of <b>Experimental Poetry</b>.</p>
        <p>
          Let’s explore the boundary of modern poetry in this bizarre world of structural beauties,
          scientific diagrams, and ASCII arts procedurally generated by computer programs!
        </p>
      </div>

      <div class="zine-paper">
        <div class="zine-part">RANDOM POEMS</div>

        <h2>Sweet Dreamer</h2>
        <p>
          I would bring stars into your dream<br>
          and pray that you can survive the Ultimate Meteor Shower!
        </p>
        <p>
          It’s a joke.<br>
          I would rather sit alongside you.<br>
          We would watch the showering stars together, overnight.<br>
          It shall be a sweet dream.
        </p>
        <p class="zine-note">(In print, a full-page ASCII meteor shower rains between the stanzas —
          the girl watches from a bench as ★ and ☆ streak down the page. See the PDF for the storm.)</p>
      </div>

      <div class="zine-paper">
        <h2>Compress the World!</h2>
        <p>
          Once a world was blessed<br>
          by the fire of unrest,<br>
          and then it was compressed<br>
          by a CPU thread!
        </p>
        <p>
          The demon from a higher dimension<br>
          played this poor world for his satisfaction.<br>
          He smashed everything into pieces.
        </p>
        <p class="zine-indent1">He mapped the pieces into random symbols.</p>
        <p class="zine-indent2">He dyed the symbols with pale pigments.</p>
        <p>
          And he glued them together,<br>
          pretending that everything is untouched.<br>
          “Isn’t it beautiful?” he asked.<br>
          Yet there was no reply as the time passed.<br>
          Because those pitiful creatures
        </p>
        <p class="zine-indent1">in the once kindled world</p>
        <p>had become</p>
        <div class="zine-broken">BROKEN</div>
        <p class="zine-indent2">pieces</p>
        <p class="zine-indent1">of</p>
        <p class="zine-indent2">symbols</p>
        <p class="zine-indent1">that will never echo a word.</p>
        <p class="zine-note">(The print zine compresses a bonfire scene into a wall of dyed symbols
          between the stanzas — a world smashed to ASCII. See the PDF.)</p>
      </div>

      <div class="zine-paper">
        <h2>Stars</h2>
        <p>
          Gazing into the deep space filled by shiny stars,<br>
          we realized that those giant solar planets<br>
          are probably
        </p>
        <pre class="zine-mono">${STARS_BOX}</pre>
        <p>millions of light years away.</p>
        <p>
          The immense universe belittles our pitiful civilization<br>
          which is now troubled by some tiny viruses<br>
          in the scope of nanometers.
        </p>
        <p>
          But it’s hard to create a space for you to imagine something small.<br>
          Therefore, I leave no space here till the very end of this page:
        </p>
        <div class="zine-void" role="img" aria-label="a page of solid black — no space at all"></div>
      </div>

      <div class="zine-paper">
        <h2>Behavior Tree in COVID Pandemic</h2>
        <p>Let’s play a game:</p>
        <ol class="zine-rules">
          <li>A circle is a “node.” Arrows linking nodes represent the relationship between nodes.
              An arrow points from a “parent node” to a “child node.”</li>
          <li>“?” means “try all child nodes; return true once a child has returned true, or return
              false if all child nodes have returned false.”</li>
          <li>“→” means “try all child nodes; return false once a child has returned false, or return
              true if all child nodes have returned true.”</li>
          <li>A question returns true or false based on your answer to it. An action always returns true.</li>
          <li>~ means try child nodes in random order; otherwise child nodes are tried from left to right
              in order. The return rule is specified by “?” or “→” in the node.</li>
        </ol>
        <p>Start from the “?” on the top of this “tree” and follow the rules above to figure out my
           daily life in this pandemic.</p>
        <pre class="zine-mono">${BEHAVIOR_TREE}</pre>
      </div>

      <div class="zine-paper">
        <div class="zine-part">POETRY COMMENTS</div>
        <p class="zine-note">
          The print zine reproduces Hagiwara Kyōjirō’s “Untitled” (1920s) here — a typeset whirl of
          arrows, bars and scattered stanzas, from William O. Gardner’s <em>Advertising Tower</em>
          (see Works Cited). The commentary below responds to it.
        </p>
        <p>
          This poem is very visually striking. It reminds me of the game books I read when I was a
          little child. In the game books, you choose an action and follow its arrow to get to the next
          scene. It was fun spending the whole afternoon playing with them.
        </p>
        <p>
          Aside from the general impression, the context is such uncanny that I can barely tell what is
          going on. Nevertheless, there are consecutive actions with close depictions of thoughts. It
          feels like an action film, with voice-over commenting the thoughts of protagonists. Also, the
          three stanzas are likely from different protagonists’ point of view.
        </p>
        <p>
          More interestingly, my friend thinks the protagonists are cars, and the poem depicts a car
          accident with explosions and flames. Now I cannot get out of this animated impression. What do
          you think about this?
        </p>
        <p>
          Undoubtfully, Hagiwara Kyojiro was a huge fan of Dadaism. And he shared the same taste on
          surrealism as his friend Hagiwara Sakutaro did. Plus, his clever implementation of typesetting
          technique turned his poems into abstract Dadaism paintings. It is indeed hard to imagine his
          poems are from the 1920s. They look like modern creations generated by computer programs.
          Considering that the concept of Turing Machine, which is the origin of modern computer, came
          out in 1936, Kyojiro is way ahead of his time!
        </p>
        <pre class="aa">${AA_TEA}</pre>
      </div>

      <div class="zine-paper">
        <h2>Postscript</h2>
        <p>
          Creating poems with special structures, tree diagrams, and ASCII arts for this zine has eaten
          away a huge chunk of my time. But it was so enjoyable that I even forgot to sleep. And I
          probably spent more time on adjusting ASCII arts than writing words, since I consider these
          cute illustrations the rhymes of my poetry as well!
        </p>
        <p>
          I don’t feel content about this short zine. And I should and would write more. This course is
          interesting and has encouraged me to explore the world of modern poetry. Thank you!
        </p>
        <pre class="aa">${AA_BYE}</pre>
      </div>

      <div class="zine-paper">
        <h2>Works Cited</h2>
        <p class="zine-cite">アスキーアート (multiple, modified for this zine). 東方AA纏メ処,
          <a href="http://touhouaamatome.jougennotuki.com/" target="_blank" rel="noopener">touhouaamatome.jougennotuki.com</a>.</p>
        <p class="zine-cite">Hagiwara, Kyōjirō. “Untitled.” <em>Advertising Tower: Japanese Modernism and
          Modernity in the 1920s</em>, by William O. Gardner, Harvard Univ. Press, 2006, p. 247.</p>
      </div>
    `;
  });
}
